---
controller_hosts:

  - name: "app-frontend.{{ GUID }}.internal"
    inventory: rh1-demo-inventory
    enabled: true

  - name: "app-backend.{{ GUID }}.internal"
    inventory: rh1-demo-inventory
    enabled: true
